# Generated by Django 3.2.7 on 2021-09-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strange_posts', '0002_auto_20210908_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='users_photo/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
